### PR TITLE
Feature/test suite with ethers.js

### PR DESCRIPTION
**Pull request by PhilippeMts**
Dear all,

This is the first pull request on this repository, which aims at providing a trustworthy integration test framework for the Ethereum JSON-RPC API to be shipped in Lotus with the Filecoin EVM runtime.

## What this PR does

We set up in this PR a `hardhat` / `hardhat-deploy` project.
The structure is briefly described in the readme.
You will find there too the main `hardhat` scripts.

This PR focuses on a test suite running on the `SimpleCoin` smart contract which constructor takes no parameter.

The test suite uses, when possible, the `ethers.js` library high-level functions to call the RPC API.
Otherwise, it goes back down to manually defining the RPC method with the [`[jsonRpcProvider.send( method , params ) ⇒ Promise< any >`](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#JsonRpcProvider-send) method.

### Comments about the test suite

- Some test cases check the shape of returned objects. Expected values are the ones described on https://github.com/ethereum/execution-apis/ ([visualizer](https://ethereum.github.io/execution-apis/api-documentation/)). @ychiaoli18 we would love to know your point of view on this. 🙏
- The test case dealing with the output of the `eth_getTransactionReceipt` and `eth_getTransactionByHash` methods BEFORE the deployment transaction is mines has NOT been included yet in this PR. We have run into a few difficulties to do it while enjoying the powerful `hardhat-deploy` convenience fixtures.

### Details on failing tests

Follows here a quick review of failing tests (Lotus commit: https://github.com/filecoin-project/lotus/commit/38891f32749ad3af93fb35e2f5fcadca21d77207).

```
  1) SimpleCoin
       Should access transaction receipt after it has been mined:

      AssertionError: expected 0 to be above 15051907. The numerical values of the given "ethers.BigNumber" and "ethers.BigNumber" inputs were compared, and they differed.
      + expected - actual

      -0
      +15051907
```

Tracking of the `cumulativeGasUsed` field has not been implemented yet.

```
  2) SimpleCoin
       Should find the transaction in block tx list:

      AssertionError: expected { …(12) } to contain keys 'parentHash', 'sha3Uncles', 'miner', 'stateRoot', 'transactionsRoot', 'receiptsRoot', 'logsBloom', 'number', 'gasLimit', 'gasUsed', 'timestamp', 'extraData', 'mixHash', 'nonce', 'size', 'transactions', and 'uncles'
      + expected - actual

       [
      -  "_difficulty"
      -  "baseFeePerGas"
      -  "difficulty"
         "extraData"
         "gasLimit"
         "gasUsed"
      +  "logsBloom"
         "miner"
      +  "mixHash"
         "nonce"
         "number"
         "parentHash"
      +  "receiptsRoot"
      +  "sha3Uncles"
      +  "size"
      +  "stateRoot"
         "timestamp"
         "transactions"
      +  "transactionsRoot"
      +  "uncles"
       ]
```

Some fields of the return object, as specified on https://github.com/ethereum/execution-apis/, cannot be found.

```
  3) SimpleCoin
       Should get block tx count:

      AssertionError: expected +0 to be above +0
      + expected - actual
```

Transactions, hydrated or not, are not part of the return value, which holds an empty list instead.

```
  4) SimpleCoin
       Should get the contract byte code at the deployed address:
     wrong param count (method 'eth_getCode'): 2 != 1
```

This test case  fails because a _default block parameter_ is expected as a second parameter there ([source](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getcode)).

Otherwise, this snippet would work fine in the test suite (but would not comply with the Ethereum RPC specs):

```js
const code = await hre.ethers.provider.send('eth_getCode', [SimpleCoin.address])
```

```
  5) SimpleCoin
       Should get storage using eth_getStorageAt:
     AssertionError: expected '0x66307832373130' to equal 10000
```

The `eth_getStorageAt` does not seem to return the right value for now. Furthermore, the subsequent test would fail as well: getting storage at the position related to an empty ERC-20 balance should return 0 but should not fail (which it does for now).

## In the backlog

Planned, according to the RFP:

- 🚧 Add the test case related to the `eth_getTransactionReceipt` and `eth_getTransactionByHash` BEFORE the deployment transaction is mined.
- Add test cases on contract with constructor parameters. We will use Raul's [simplified OpenZeppelin ERC20](https://github.com/filecoin-project/fvm-example-actors/tree/main/erc20-sans-events).
- Implement the test suites with `web3.js` in addition to `ethers.js`.

Should the following items be added to the backlog @ychiaoli18 ?

- Add a small test to check if the connected node is part of a Filecoin network or not, so that we may run the Filecoin-specific parts only in this case, and have the whole project be compatible with other Ethereum networks (ganache,…) by default. This could help increase our confidence in the test suite.

### CODE REVIEW

**Comment by PhilippeMts** [comment]
Please note that because of conflicting peer dependencies, we recommend installing modules with the `npm install --force` option for now.

This is fixed on pending commits on the `feature/test-on-pending-tx-receipt` branch.

**Comment by ychiaoli18** [comment]
> Some test cases check the shape of returned objects. Expected values are the ones described on https://github.com/ethereum/execution-apis/ ([visualizer](https://ethereum.github.io/execution-apis/api-documentation/)).

This is awesome! We should check the response against the API spec you provided. 

> Add a small test to check if the connected node is part of a Filecoin network or not, so that we may run the Filecoin-specific parts only in this case, and have the whole project be compatible with other Ethereum networks (ganache,…) by default. This could help increase our confidence in the test suite.

This is a good idea and we should do it. Do we know which part of the test may require this feature?

**Comment by PhilippeMts** [comment]
Early merge of the current PR following @ychiaoli18 's advice in the chat in order to speed up progress and facilitate readability before the release of version `1.0.0`.

Same decision taken for https://github.com/polyphene/lotus-eth-api-integration-tests/pull/2, https://github.com/polyphene/lotus-eth-api-integration-tests/pull/3 & https://github.com/polyphene/lotus-eth-api-integration-tests/pull/4.

**Comment by PhilippeMts** [comment]
> > Add a small test to check if the connected node is part of a Filecoin network or not, so that we may run the Filecoin-specific parts only in this case, and have the whole project be compatible with other Ethereum networks (ganache,…) by default. This could help increase our confidence in the test suite.
> 
> This is a good idea and we should do it. Do we know which part of the test may require this feature?

At the moment, I think we mainly have to focus on the `from` field of write methods, and that should be enough 🤞

👉 opening https://github.com/polyphene/lotus-eth-api-integration-tests/issues/5

**Pull request merged**
